name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  validate:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Get changed files
      id: files
      uses: jitterbit/get-changed-files@v1
      with:
        format: 'csv'
    - name: Colony validate blueprints
      uses: QualiSystemsLab/colony-validate-bp-action@v0.0.1
      with:
        space: Trial
        files_list: ${{ steps.files.outputs.added_modified  }}
        colony_token: ${{ secrets.COLONY_TOKEN }}
  jobA:
    needs: validate
    runs-on: ubuntu-latest

    steps:
    - name: Sleep for 10s
      uses: juliangruber/sleep-action@v1
      with:
        time: 40s
  jobB:
    needs: validate
    runs-on: ubuntu-latest

    steps:
    - name: Start sandbox
      id: start-sandbox
      uses: QualiSystemsLab/colony-start-sb-action@dev
      with:
        space: Trial
        blueprint_name: empty-bp-empty-app
        sandbox_name: empty-bp-empty-app sandbox
        colony_token: ${{ secrets.COLONY_TOKEN }}
        branch: master
        duration: 30
        timeout: 28
    - name: End sandbox on failure
      if: failure() && steps.start-sandbox.outputs.sandbox_id != ''
      uses: QualiSystemsLab/colony-end-sb-action@dev
      with:
        space: Trial
        sandbox_id: ${{steps.start-sandbox.outputs.sandbox_id}}
        colony_token: ${{ secrets.COLONY_TOKEN }}

    outputs:
      sandbox_id: ${{ steps.start-sandbox.outputs.sandbox_id }}
  finish-all:
    needs: [jobA, jobB]
    runs-on: ubuntu-latest

    steps:
    - name: Stop sandbox
      uses: QualiSystemsLab/colony-end-sb-action@dev
      with:
        space: Trial
        sandbox_id: ${{needs.jobB.outputs.sandbox_id}}
        colony_token: ${{ secrets.COLONY_TOKEN }}
