name: CI
on:
  push:
    branches:
      - master
    pull_request:
      branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Get changed files
      id: files
      uses: jitterbit/get-changed-files@v1
      with:
        format: 'csv'
    - name: Colony validate blueprints
      uses: kalsky/colony-validate-bp-action@master
      with:
        space: Trial
        fileslist: ${{ steps.files.outputs.added_modified  }}
        colony_token: ${{ secrets.COLONY_TOKEN }}